name: Test And Deployment Pipeline
on:
  workflow_dispatch:
  push:
    branches: [ "ytdb-fork-3.8-dev" ]
  pull_request:
    branches: [ "ytdb-fork-3.8-dev" ]
env:
  MODULES: ':gremlin-core,:gremlin-driver,:gremlin-server,:gremlin-test,:gremlin-console'
jobs:
  test:
    name: Test on ${{ matrix.platform.os }} - JDK ${{ matrix.java }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        java: [ '17' ]
        platform:
          - os: ubuntu-latest
            arch: x64
            mvn_opts: '-Dmaven.test.failure.ignore=true'
          - os: ubuntu-24.04-arm
            arch: arm64
            mvn_opts: '-Dmaven.test.failure.ignore=true'
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v6

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          architecture: ${{ matrix.platform.arch }}
          cache: 'maven'

      - name: Run Maven Tests
        run: mvn -am -pl ${{ env.MODULES }} clean package -B ${{ matrix.platform.mvn_opts }}
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' # Only deploy on push, not PRs
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v6

      - name: Set up JDK 17 settings
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          # Repository Credentials
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Maven deploy
        # Deploy to Maven Central as SNAPSHOT
        run: mvn clean deploy -am -pl ${{ MODULES}} -DskipTests -B
        env:
          # Credentials mapped to environment variables
          MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
  notify-failure:
    name: Notify build failure on Zulip
    needs: [ test, deploy]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Send Zulip notification
        uses: zulip/github-actions-zulip/send-message@v1
        with:
          api-key: ${{ secrets.ZULIP_API_KEY }}
          email: ci-status-bot@youtrackdb.zulipchat.com
          organization-url: 'https://youtrackdb.zulipchat.com'
          to: 'ytdb'
          type: 'stream'
          topic: 'ci status'
          content: |
            **BUILD FAILED** :rotating_light:
            Build failed for commit ${{ github.sha }}.
            [View Run Logs](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})