name: Test And Deployment Pipeline
on:
  workflow_dispatch:
  push:
    branches: [ "ytdb-fork-3.8-dev" ]
  pull_request:
    branches: [ "ytdb-fork-3.8-dev" ]
env:
  MODULES: ':gremlin-core,:gremlin-driver,:gremlin-server,:gremlin-test,:gremlin-console'
jobs:
  test:
    name: Test on ${{ matrix.platform.os }} - JDK ${{ matrix.java }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        java: [ '17' ]
        platform:
          - os: ubuntu-latest
            arch: x64
            mvn_opts: '-Dmaven.test.failure.ignore=true'
          - os: ubuntu-24.04-arm
            arch: arm64
            mvn_opts: '-Dmaven.test.failure.ignore=true'
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v6

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          architecture: ${{ matrix.platform.arch }}
          cache: 'maven'
          overwrite-settings: false

      - name: Run Maven Tests
        run: mvn -s .github/workflows/settings.xml -am -pl ${{ env.MODULES }} clean package -B ${{ matrix.platform.mvn_opts }}
        env:
          MAVEN_MIROR_USERNAME: ${{ secrets.MAVEN_MIROR_USERNAME }}
          MAVEN_MIROR_PASSWORD: ${{ secrets.MAVEN_MIROR_PASSWORD }}
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()  # Run this even if Maven crashed for non-test reasons
        with:
          files: |
            target/surefire-reports/*.xml
            target/failsafe-reports/*.xml
          action_fail: true
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' # Only deploy on push, not PRs
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v6

      - name: Set up JDK 17 settings
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          overwrite-settings: false

      - name: Maven deploy
        # Deploy to Maven Central as SNAPSHOT
        run: mvn -s .github/workflows/settings.xml clean deploy -am -pl ${{ env.MODULES}} -DskipTests -B
        env:
          # Credentials mapped to environment variables
          MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          MAVEN_MIROR_USERNAME: ${{ secrets.MAVEN_MIROR_USERNAME }}
          MAVEN_MIROR_PASSWORD: ${{ secrets.MAVEN_MIROR_PASSWORD }}
  notify-failure:
    name: Notify build failure on Zulip
    needs: [ test, deploy]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Send Zulip notification
        uses: zulip/github-actions-zulip/send-message@v1
        with:
          api-key: ${{ secrets.ZULIP_API_KEY }}
          email: ci-status-bot@youtrackdb.zulipchat.com
          organization-url: 'https://youtrackdb.zulipchat.com'
          to: 'ytdb'
          type: 'stream'
          topic: 'ci status'
          content: |
            **BUILD FAILED** :rotating_light:
            Build failed on branch `${{ github.ref_name }} for commit ${{ github.sha }} for repo ${{ github.repository }}.
            [View Run Logs](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
      - name: Send Zulip notification
        if: steps.previous_run.outputs.previous_conclusion == 'failure'
        uses: zulip/github-actions-zulip/send-message@v1
        with:
          api-key: ${{ secrets.ZULIP_API_KEY }}
          email: ci-status-bot@youtrackdb.zulipchat.com
          organization-url: 'https://youtrackdb.zulipchat.com'
          to: 'ytdb'
          type: 'stream'
          topic: 'ci status'
          content: |
            **BUILD FIXED** :white_check_mark:
            Build fixed on branch `${{ github.ref_name }}` for commit ${{ github.sha }} for repo ${{ github.repository }}.
            [View Run Logs](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})